### ISSUE TITLE
Errors with long UTRs

### ISSUE THREAD

**Issue by 3mma-mack** [3mma-mack/Riboviz-honours#2]
When running check_fasta_gff on the long UTR gff and fasta I received the following error

```
(riboviz) [s1734289@node3a05(eddie) riboviz]$ python -m riboviz.tools.check_fasta_gff -f D-Sp_2018/original_genome_gff/S_pombe_full_UTR.fasta -g D-Sp_2018/original_genome_gff/S_pombe_full_UTR_fixed.gff3                    Created by: RiboViz
Date: 2021-03-22 10:59:01.138786
Command-line tool: /exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/tools/check_fasta_gff.py
File: /exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/tools/check_fasta_gff.py
Version: commit b75c1ba0e2a541d6f256e2d295b352a3aef969a9 date 2021-02-25 16:16:12+00:00

Traceback (most recent call last):
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/tools/check_fasta_gff.py", line 121, in <module>
    invoke_check_fasta_gff()
  File "/exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/tools/check_fasta_gff.py", line 111, in invoke_check_fasta_gff
    is_verbose=is_verbose)
  File "/exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/check_fasta_gff.py", line 403, in check_fasta_gff
    start_codons=start_codons)
  File "/exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/check_fasta_gff.py", line 214, in get_fasta_gff_cds_issues
    sort_attribute_values=True)
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/lib/python3.7/site-packages/gffutils/create.py", line 1292, in create_db
    c.create()
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/lib/python3.7/site-packages/gffutils/create.py", line 507, in create
    self._populate_from_lines(self.iterator)
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/lib/python3.7/site-packages/gffutils/create.py", line 589, in _populate_from_lines
    self._insert(f, c)
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/lib/python3.7/site-packages/gffutils/create.py", line 530, in _insert
    cursor.execute(constants._INSERT, feature.astuple())
sqlite3.InterfaceError: Error binding parameter 11 - probably unsupported type.

```
 I'm not sure why it is an unsupported type

**Comment by 3mma-mack** [comment]
I decided to do a test run with the Duncan & Mata dataset and found the following error in the Nextflow Bam to H5 error logs

```
Warning message:
In mclapply(genes, function(gene) { :
  all scheduled cores encountered errors in user code
Error in sum(output) : invalid 'type' (character) of argument
Calls: h5writeAttribute.integer -> h5writeAttribute.array
Execution halted

```

again, looks like it is a type issue, just need to find where
